version: '3'

services:
  web:
    platform: linux/amd64
    image: baritomarket-web-dev:latest
    build:
      context: .
      args:
        - RAILS_ENV=development
        - RACK_ENV=development
    environment:
      - DB_USER=barito
      - DB_HOST=db
      - DB_NAME=barito
      - DB_PASSWORD=barito
      - REDIS_CACHE_HOST=redis:6379
      - RAILS_ENV=development
      - RACK_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - DB_POOL=5
      - DB_TIMEOUT=60
      - CAS_BASE_URL=""
    volumes:
      - .:/app
    ports:
      - 8080:8080

  scheduler:
    platform: linux/amd64
    image: baritomarket-web-dev:latest
    depends_on:
      - web
    command: ["sidekiq"]
    environment:
      - DB_USER=barito
      - DB_HOST=db
      - DB_NAME=barito
      - DB_PASSWORD=barito
      - REDIS_CACHE_HOST=redis:6379
      - RAILS_ENV=development
      - RACK_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - DB_POOL=5
      - DB_TIMEOUT=60
      - CAS_BASE_URL=""
    volumes:
      - .:/app

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=barito
      - POSTGRES_DB=barito
      - POSTGRES_PASSWORD=barito

  redis:
    image: redis:5-alpine
