source 'https://rubygems.org'

gem 'berkshelf', '<= 7.0.2'
gem 'bootstrap', '~> 4.3.1'
gem 'devise', "~> 4.8.0"
gem 'elasticsearch'
gem 'execjs', '<= 2.7.0'
gem 'faker', '<= 1.8.7'
gem 'figaro', '<= 1.1.1'
gem 'jar-dependencies', '<= 0.3.12'
gem 'jbuilder', '<= 2.7.0'
gem 'jquery-rails'
gem 'kaminari'
gem 'knife-solo', '<= 0.7.0.pre3'
gem 'mini_racer', '~> 0.2.4'
gem 'newrelic_rpm'
gem 'orderly'
gem 'pg', '<= 1.0.0'
gem 'puma', '<= 3.12.7'
gem 'pundit'
gem 'rails', '~> 5.2.2.1'
gem 'redis', '<= 4.0.2'
gem 'select2-rails'
gem 'rufus-mnemo'
gem 'sass-rails'
gem 'sidekiq', '<= 5.2.10'
gem 'slim', '<= 3.0.9'
gem 'slim-rails', '<= 3.1.3'
gem 'typhoeus', '<= 1.3.0'
gem 'uglifier'
gem 'wisper', '<= 2.0.0'
gem 'filterrific'
gem 'dogstatsd-ruby'
gem 'prometheus-client'
gem 'jaeger-client'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'oauth2', '~> 1.4.9'
gem 'jwt'

group :development, :test do
  gem 'cane', '<= 3.0'
  gem 'capybara', '<= 3.2.1'
  gem 'coveralls', '<= 0.8'
  gem 'database_cleaner', '<= 1.7'
  gem 'factory_bot_rails', '<= 4.10.0'
  gem 'rspec-rails', '<= 3.7.2'
  gem 'rubocop', '<= 0.56'
  gem 'rubocop-rspec', '<= 1.25'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', '~> 4.0'
  gem 'simplecov', '<= 0.14'
  gem 'simplecov-console', '<= 0.4'
  gem 'timecop', '<= 0.9.1'
  gem 'webdrivers', '~> 4.0'
  gem 'webmock', '<= 3.4.1'
  gem 'fakeredis'
  gem 'pry', '<= 0.11.3'
  gem 'pry-nav'
end

group :development do
  gem 'listen', '<= 3.1.5'
  gem 'spring', '<= 2.0.2'
  gem 'spring-watcher-listen', '<= 2.0.1'
  gem 'web-console', '<= 3.6.2'
  gem 'awesome_print'
end
