Api::AppsController.subscribe(DatadogListener.new)
Api::V2::AppsController.subscribe(DatadogListener.new)
AppsController.subscribe(DatadogListener.new)
AppGroupsController.subscribe(DatadogListener.new)

Api::AppsController.subscribe(PrometheusListener.new)
Api::V2::AppsController.subscribe(PrometheusListener.new)
AppsController.subscribe(PrometheusListener.new)
AppGroupsController.subscribe(PrometheusListener.new)

BaritoBlueprint::Provisioner.subscribe(ProvisioningListener.new)
Api::AppsController.subscribe(RedisCacheListener.new)
AppGroupsController.subscribe(RedisCacheListener.new)
AppsController.subscribe(RedisCacheListener.new)
GateClient.subscribe(RedisCacheListener.new)
